// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8NI-bosU-ZhWEUQrM1XMVZ2sC39YP8Tk',
    appId: '1:526230290583:web:6fd0cf8000d2b74790e9d2',
    messagingSenderId: '526230290583',
    projectId: 'gsc23-12e94',
    authDomain: 'gsc23-12e94.firebaseapp.com',
    storageBucket: 'gsc23-12e94.appspot.com',
    measurementId: 'G-FS97X61QXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfZ7vjhlavY45bckzTsSKbCmVyHyyrNM',
    appId: '1:526230290583:android:9d0255e043c95cb790e9d2',
    messagingSenderId: '526230290583',
    projectId: 'gsc23-12e94',
    storageBucket: 'gsc23-12e94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFK2MOGyYaVSBy1PVyCpppdtiPmwnAKgg',
    appId: '1:526230290583:ios:a9c8d32f766bebb290e9d2',
    messagingSenderId: '526230290583',
    projectId: 'gsc23-12e94',
    storageBucket: 'gsc23-12e94.appspot.com',
    iosClientId: '526230290583-jv0epk2pn14jnf3e6pm1uo4d75l8eqb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.headhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFK2MOGyYaVSBy1PVyCpppdtiPmwnAKgg',
    appId: '1:526230290583:ios:a9c8d32f766bebb290e9d2',
    messagingSenderId: '526230290583',
    projectId: 'gsc23-12e94',
    storageBucket: 'gsc23-12e94.appspot.com',
    iosClientId: '526230290583-jv0epk2pn14jnf3e6pm1uo4d75l8eqb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.headhome',
  );
}
